name: Deployment

on:
  create:
    tags:
      - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/linux_amd64/release/jira-rss-client
